#define MSGJPN001		"接続を中止しました."
#define MSGJPN002		"接続を中止しました."
#define MSGJPN003		"\r\n再接続します.\r\n"
#define MSGJPN004		"切断しました"
#define MSGJPN005		"接続が切断されました."
#define MSGJPN006		"FireWallにログインできません."
#define MSGJPN007		"ホスト %s に接続できません."
#define MSGJPN008		"ログインできません."
#define MSGJPN009		"接続できません."
#define MSGJPN010		"FireWallのホスト名が設定されていません."
#define MSGJPN011		"ホスト名がありません."
#define MSGJPN012		"MD5を使用します."
#define MSGJPN013		"SHA-1を使用します."
#define MSGJPN014		"MD4(S/KEY)を使用します."
#define MSGJPN015		"ワンタイムパスワードが処理できません"
#define MSGJPN016		"ホスト %s を探しています."
#define MSGJPN017		"%sホスト %s (%s (%d)) に接続しています."
#define MSGJPN018		"%sホスト %s (%d) に接続しています."
#define MSGJPN019		"ホスト %s が見つかりません."
#define MSGJPN020		"%sホスト %s (%d) に接続しています."
#define MSGJPN021		"SOCKSサーバ %s が見つかりません."
#define MSGJPN022		"SOCKSサーバ %s (%d) に接続しています。"
#define MSGJPN023		"SOCKSサーバに接続できません. (Err=%d)"
#define MSGJPN024		"SOCKSサーバに接続できません. (Err=%d)"
#define MSGJPN025		"接続しました."
#define MSGJPN026		"接続できません."
#define MSGJPN027		"ソケットが作成できません."
#define MSGJPN028		"SOCKSサーバに接続できません. (Err=%d)"
#define MSGJPN029		"SOCKSサーバに接続できません. (Err=%d)"
#define MSGJPN030		"Listenソケットが作成できません."
#define MSGJPN031		"PORTコマンドが受け付けられません."
#define MSGJPN032		"接続はユーザによって中止されました."
#define MSGJPN033		"SOCKSのコマンドが送れませんでした (Cmd = %04X)"
#define MSGJPN034		"SOCKS5のコマンドに対するリプライが受信できませんでした"
#define MSGJPN035		"SOCKS4のコマンドに対するリプライが受信できませんでした"
#define MSGJPN036		"SOCKSサーバの認証方式が異なります."
#define MSGJPN037		"SOCKSサーバに認証されませんでした."
#define MSGJPN038		"名前"
#define MSGJPN039		"日付"
#define MSGJPN040		"サイズ"
#define MSGJPN041		"種類"
#define MSGJPN042		"名前"
#define MSGJPN043		"日付"
#define MSGJPN044		"サイズ"
#define MSGJPN045		"種類"
#define MSGJPN046		"属性"
#define MSGJPN047		"所有者"
#define MSGJPN048		"テンポラリファイルが読み出せません."
#define MSGJPN049		"ファイル一覧の取得に失敗しました."
#define MSGJPN050		"検索（ローカル）"
#define MSGJPN051		"検索（ホスト）"
#define MSGJPN052		"削除： %s"
#define MSGJPN053		"作成： %s"
#define MSGJPN054		"転送： %s"
#define MSGJPN055		"削除： %s"
#define MSGJPN056		"作成： %s"
#define MSGJPN057		"転送： %s"
#define MSGJPN058		"%d個のファイルを転送します."
#define MSGJPN059		"転送するファイルはありません."
#define MSGJPN060		"%d個のフォルダを作成します."
#define MSGJPN061		"作成するフォルダはありません."
#define MSGJPN062		"%d個のファイル／フォルダを削除します."
#define MSGJPN063		"削除するファイル／フォルダはありません."
#define MSGJPN064		"名前を変更してアップロード"
#define MSGJPN065		"名前を変更してダウンロード"
#define MSGJPN066		"削除（ローカル）"
#define MSGJPN067		"削除（ホスト）"
#define MSGJPN068		"名前変更（ローカル）"
#define MSGJPN069		"名前変更（ホスト）"
#define MSGJPN070		"フォルダ作成（ローカル）"
#define MSGJPN071		"フォルダ作成（ホスト）"
#define MSGJPN072		"フォルダ変更（ローカル）"
#define MSGJPN073		"フォルダ変更（ホスト）"
#define MSGJPN074		"ローカル側のファイル容量を計算します。"
#define MSGJPN075		"ホスト側のファイル容量を計算します。"
#define MSGJPN076		"ローカル側のファイル容量"
#define MSGJPN077		"ホスト側のファイル容量"
#define MSGJPN078		"フォルダ作成"
#define MSGJPN079		"フォルダ作成"
#define MSGJPN080		"フォルダ削除"
#define MSGJPN081		"ファイル削除"
#define MSGJPN082		"フォルダ作成"
#define MSGJPN083		"フォルダ削除"
#define MSGJPN084		"ファイル削除"
#define MSGJPN085		"%sという名前のファイルはダウンロードできません."
#define MSGJPN086		"ダウンロード"
#define MSGJPN087		"ファイル一覧取得"
#define MSGJPN088		"スキップ"
#define MSGJPN089		"ファイル %s はスキップします."
#define MSGJPN090		"コマンドが受け付けられません."
#define MSGJPN091		"ダウンロードのために"
#define MSGJPN092		"コマンドが受け付けられません."
#define MSGJPN093		"アドレスが取得できません."
#define MSGJPN094		"受信はタイムアウトで失敗しました."
#define MSGJPN095		"ファイル %s が作成できません."
#define MSGJPN096		"ディスクがいっぱいで書き込めません."
#define MSGJPN097		"ファイル一覧の取得を中止しました."
#define MSGJPN098		"ファイル一覧"
#define MSGJPN099		"ダウンロードを中止しました. (%d Sec. %d B/S)."
#define MSGJPN100		"ダウンロードを中止しました."
#define MSGJPN101		"ファイル一覧の取得は正常終了しました. (%d Bytes)"
#define MSGJPN102		"ダウンロードは正常終了しました. (%d Sec. %d B/S)."
#define MSGJPN103		"ダウンロードは正常終了しました. (%d Bytes)"
#define MSGJPN104		"アップロード"
#define MSGJPN105		"ファイル %s が読み出せません."
#define MSGJPN106		"スキップ"
#define MSGJPN107		"ファイル %s はスキップします."
#define MSGJPN108		"コマンドが受け付けられません."
#define MSGJPN109		"アップロードのために"
#define MSGJPN110		"コマンドが受け付けられません."
#define MSGJPN111		"アドレスが取得できません."
#define MSGJPN112		"ファイル %s がオープンできません."
#define MSGJPN113		"アップロードを中止しました. (%d Sec. %d B/S)."
#define MSGJPN114		"アップロードを中止しました."
#define MSGJPN115		"アップロードは正常終了しました. (%d Sec. %d B/S)."
#define MSGJPN116		"アップロードは正常終了しました."
#define MSGJPN117		"完了"
#define MSGJPN118		"中止"
#define MSGJPN119		"バイナリ"
#define MSGJPN120		"アスキー"
#define MSGJPN121		"無変換"
#define MSGJPN122		"JIS"
#define MSGJPN123		"EUC"
#define MSGJPN124		"削除（ローカル）"
#define MSGJPN125		"削除（ホスト）"
#define MSGJPN126		"WS_FTP.INIファイル"
#define MSGJPN127		"基本"
#define MSGJPN128		"拡張"
#define MSGJPN129		"文字コード"
#define MSGJPN130		"ダイアルアップ"
#define MSGJPN131		"高度"
#define MSGJPN132		"ホストの設定"
#define MSGJPN133		"GMT%+02d:00 (日本)"
#define MSGJPN134		"使用しない"
#define MSGJPN135		"自動認識"
#define MSGJPN136		"OTP MD4, S/KEY"
#define MSGJPN137		"OTP MD5"
#define MSGJPN138		"OTP SHA-1"
#define MSGJPN139		"自動認識"
#define MSGJPN140		"ACOS"
#define MSGJPN141		"VAX VMS"
#define MSGJPN142		"IRMX"
#define MSGJPN143		"ACOS-4"
#define MSGJPN144		"Stratus"
#define MSGJPN145		"フォルダを変更できません."
#define MSGJPN146		"フォルダを作成できません."
#define MSGJPN147		"フォルダを削除できません."
#define MSGJPN148		"フォルダを削除できません."
#define MSGJPN149		"ファイルを削除できません."
#define MSGJPN150		"ファイルを削除できません."
#define MSGJPN151		"ファイル名変更ができません."
#define MSGJPN152		"テンポラリフォルダ「%s」がありません"
#define MSGJPN153		"フォルダ「%s」を使用します"
#define MSGJPN154		"接続"
#define MSGJPN155		"クイック接続"
#define MSGJPN156		"切断"
#define MSGJPN157		"ダウンロード"
#define MSGJPN158		"アップロード"
#define MSGJPN159		"ミラーリングアップロード"
#define MSGJPN160		"削除"
#define MSGJPN161		"名前変更"
#define MSGJPN162		"フォルダ作成"
#define MSGJPN163		"一つ上のフォルダへ"
#define MSGJPN164		"フォルダの移動"
#define MSGJPN165		"アスキー転送モード"
#define MSGJPN166		"バイナリ転送モード"
#define MSGJPN167		"ファイル名で転送モード切替え"
#define MSGJPN168		"表示を更新"
#define MSGJPN169		"一覧"
#define MSGJPN170		"詳細"
#define MSGJPN171		"ホストの漢字コードはEUC"
#define MSGJPN172		"ホストの漢字コードはJIS"
#define MSGJPN173		"漢字コードの変換なし"
#define MSGJPN174		"半角カナを全角に変換"
#define MSGJPN175		"フォルダ同時移動"
#define MSGJPN176		"受信中止"
#define MSGJPN177		"設定名「%s」はありません."
#define MSGJPN178		"設定名が指定されていません."
#define MSGJPN179		"ホスト名と設定名の両方が指定されています."
#define MSGJPN180		"オプション「%s」が間違っています."
#define MSGJPN181		"ホスト名と設定名の両方が指定されています."
#define MSGJPN182		"ビューワの起動に失敗しました. (ERROR=%d)"
#define MSGJPN183		"JRE32.DLL 無し"
#define MSGJPN184		"JRE32.DLL Ver %x.%x (C) 山田和夫さん"
#define MSGJPN185		"フォルダを選択してください"
#define MSGJPN186		"ユーザ"
#define MSGJPN187		"転送１"
#define MSGJPN188		"転送２"
#define MSGJPN189		"転送３"
#define MSGJPN190		"ミラーリング"
#define MSGJPN191		"操作"
#define MSGJPN192		"表示"
#define MSGJPN193		"接続/切断"
#define MSGJPN194		"FireWall"
#define MSGJPN195		"ツール"
#define MSGJPN196		"サウンド"
#define MSGJPN197		"その他"
#define MSGJPN198		"オプション"
#define MSGJPN199		"ファイル名"
#define MSGJPN200		"ファイル名"
#define MSGJPN201		"属性"
#define MSGJPN202		"ファイル名"
#define MSGJPN203		"ファイル名"
#define MSGJPN204		"FWユーザ名→ FWパスワード→ SITE ホスト名"
#define MSGJPN205		"FWユーザ名→ FWパスワード→ USER ユーザ名@ホスト名"
#define MSGJPN206		"FWユーザ名→ FWパスワード"
#define MSGJPN207		"USER ユーザ名@ホスト名"
#define MSGJPN208		"OPEN ホスト名"
#define MSGJPN209		"SOCKS4"
#define MSGJPN210		"SOCKS5 (認証なし)"
#define MSGJPN211		"SOCKS5 (ユーザ名、パスワード認証)"
#define MSGJPN212		"使用しない"
#define MSGJPN213		"自動認識"
#define MSGJPN214		"OTP MD4,S/KEY"
#define MSGJPN215		"OTP MD5"
#define MSGJPN216		"OTP SHA-1"
#define MSGJPN217		"ビューワの選択"
#define MSGJPN218		"実行ファイル\0*.exe;*.com;*.bat\0全てのﾌｧｲﾙ\0*\0"
#define MSGJPN219		"Waveファイル"
#define MSGJPN220		"ダイアルアップを切断しています."
#define MSGJPN221		"ダイアルアップで接続しています."
#define MSGJPN222		"ダイアルアップが使えません(RasDialDlg)"
#define MSGJPN223		"%s に接続しています..."
#define MSGJPN224		"不明なエラー"
#define MSGJPN225		"ダイアルアップ接続"
#define MSGJPN226		"ポートを開いています..."
#define MSGJPN227		"ポートが開かれました"
#define MSGJPN228		"ダイアル中..."
#define MSGJPN229		"ダイアル完了"
#define MSGJPN230		"全デバイスが接続されました"
#define MSGJPN231		"ユーザ名とパスワードを検証中..."
#define MSGJPN232		"再検証中..."
#define MSGJPN233		"パスワードを変更して下さい"
#define MSGJPN234		"検証が終了しました"
#define MSGJPN235		"接続しました"
#define MSGJPN236		"切断しました"
#define MSGJPN237		"接続処理中..."
#define MSGJPN238		"%s への接続"
#define MSGJPN239		"# このファイルは編集しないでください。\n"
#define MSGJPN240		"INIファイルに設定が保存できません"
#define MSGJPN241		"送信はタイムアウトで失敗しました."
#define MSGJPN242		"受信はタイムアウトで失敗しました."
#define MSGJPN243		"受信はタイムアウトで失敗しました."
#define MSGJPN244		"固定長の受信が失敗しました"
#define MSGJPN245		"ローカル"
#define MSGJPN246		"ホスト"
#define MSGJPN247		"選択%d個（%s）"
#define MSGJPN248		"ローカル空 %s"
#define MSGJPN249		"転送待ちファイル%d個"
#define MSGJPN250		"受信中 %s"
#define MSGJPN251		"Err：シード文字列"
#define MSGJPN252		"Err：シード文字列"
#define MSGJPN253		"Err：シーケンス番号"
#define MSGJPN254		"MS Shell Dlg"
#define MSGJPN255		"アップロード(&U)"
#define MSGJPN256		"名前を変えてアップロード(&P)..."
#define MSGJPN257		"全てをアップロード"
#define MSGJPN258		"削除(&R)"
#define MSGJPN259		"名前変更(&N)..."
#define MSGJPN260		"フォルダ作成(&K)..."
#define MSGJPN261		"ファイル容量計算(&Z)"
#define MSGJPN262		"最新の情報に更新(&F)"
#define MSGJPN263		"ダウンロード(&D)"
#define MSGJPN264		"名前を変えてダウンロード(&W)..."
#define MSGJPN265		"ファイルとしてダウンロード(&I)"
#define MSGJPN266		"全てをダウンロード"
#define MSGJPN267		"削除(&R)"
#define MSGJPN268		"名前変更(&N)..."
#define MSGJPN269		"属性変更(&A)..."
#define MSGJPN270		"フォルダ作成(&K)..."
#define MSGJPN271		"URLをクリップボードへコピー(&C)"
#define MSGJPN272		"ファイル容量計算(&Z)"
#define MSGJPN273		"最新の情報に更新(&F)"
#define MSGJPN274		"開く(&O)"
#define MSGJPN275		"%sで開く(&%d)"
#define MSGJPN276		"WS_FTP.INI\0ws_ftp.ini\0全てのﾌｧｲﾙ\0*\0"
#define MSGJPN277		"Waveファイル\0*.wav\0全てのファイル\0*\0"
#define MSGJPN278		"理由：%s"
#define MSGJPN279		"Listenソケットが取得できません"
#define MSGJPN280		"Dataソケットが取得できません"
#define MSGJPN281		"PASVモードで接続できません"
#define MSGJPN282		"INIファイル名が指定されていません"
#define MSGJPN283		"INIファイル指定："
#define MSGJPN284		"http://sourceforge.jp/projects/ffftp/"
#define MSGJPN285		"レジストリエディタが起動できませんでした"
#define MSGJPN286		"設定ファイルの保存"
#define MSGJPN287		"Regファイル\0*.reg\0全てのファイル\0*\0"
#define MSGJPN288		"INIファイル\0*.ini\0全てのファイル\0*\0"
#define MSGJPN289		"Agilent Logic analyzer"
#define MSGJPN290		"Regファイル\0*.reg\0INIファイル\0*.ini\0全てのファイル\0*\0"
#define MSGJPN291		"設定をファイルから復元"
#define MSGJPN292		"設定をファイルから復元するためには、FFFTPを再起動してください。"
#define MSGJPN293		"設定ファイルは拡張子が.regか.iniでなければなりません。"
#define MSGJPN294		"USER FWユーザ名:FWパスワード@ホスト名"
#define MSGJPN295		"シバソク WL"
#define MSGJPN296		"読み取り専用ファイルです。読み取り専用属性を解除しますか？"
#define MSGJPN297		"%s は不正なファイル名です。\r\nこのファイルはダウンロードされません。"
#define MSGJPN298		"OLEの初期化に失敗しました。"
#define MSGJPN299		"コマンドラインにマスターパスワードが指定されていません"
#define MSGJPN300		"デフォルトのマスターパスワードが使われます．\r\nマルウェアの攻撃を防ぐため，固有のマスターパスワードを設定することをおすすめします"
#define MSGJPN301		"マスターパスワードが設定と一致しません．安全のため設定の保存を行いません．"
#define MSGJPN302		"確認用データが壊れているため，マスターパスワードの正当性を確認できませんでした．"
#define MSGJPN303		"マスターパスワードを変更しました"
#define MSGJPN304		"指定されたマスターパスワードが登録されたものと一致しません．\r\n再度入力しますか？\r\n「いいえ」を選ぶと記憶されたFTPパスワードは利用できません．"
#define MSGJPN305		"Shift_JIS"
#define MSGJPN306		"UTF-8"
#define MSGJPN307		"ホストの漢字コードはShift_JIS"
#define MSGJPN308		"ホストの漢字コードはUTF-8"
#define MSGJPN309		"ローカルの漢字コードはShift_JIS"
#define MSGJPN310		"ローカルの漢字コードはEUC"
#define MSGJPN311		"ローカルの漢字コードはJIS"
#define MSGJPN312		"ローカルの漢字コードはUTF-8"
#define MSGJPN313		"暗号化"
#define MSGJPN314		"通信は暗号化されていません.\r\n第三者にパスワードおよび内容を傍受される可能性があります."
#define MSGJPN315		"FTP over Explicit SSL/TLS (FTPES)を使用します."
#define MSGJPN316		"FTP over Implicit SSL/TLS (FTPIS)を使用します."
#define MSGJPN317		"SSH FTP (SFTP)を使用します."
#define MSGJPN318		"OpenSSLが読み込まれました."
#define MSGJPN319		"OpenSSLがインストールされていません.\r\n通信の暗号化は行われません."
#define MSGJPN320		"特殊機能"
#define MSGJPN321		"プロセスの保護に必要な関数を取得できませんでした."
#define MSGJPN322		"デバッガが検出されました."
#define MSGJPN323		"信頼できないDLLをアンロードできませんでした."
#define MSGJPN324		"プロセスの保護に必要な関数をフックできませんでした."
#define MSGJPN325		"新しいマスターパスワードが一致しません."
#define MSGJPN326		"この証明書を信頼し,通信を続行するには「はい」を選択してください.\r\nCNの一致: %s\r\n検証に成功: %s\r\n\r\n%s"
#define MSGJPN327		"はい"
#define MSGJPN328		"いいえ"
#define MSGJPN329		"UTF-8 BOM"
#define MSGJPN330		"ホストの漢字コードはUTF-8 BOM"
#define MSGJPN331		"ローカルの漢字コードはUTF-8 BOM"
#define MSGJPN332		"自動"
#define MSGJPN333		"TCP/IPv4"
#define MSGJPN334		"TCP/IPv6"
#define MSGJPN335		"毎回尋ねる"
#define MSGJPN336		"全て後で上書き"
#define MSGJPN337		"全て後でリジューム"
#define MSGJPN338		"全てスキップ"
