
#define MSGJPN001		u8("Connection cancelled.")
#define MSGJPN002		u8("Connection cancelled.")
#define MSGJPN003		u8("\r\nReconnect.\r\n")
#define MSGJPN004		u8("Disconnect.")
#define MSGJPN005		u8("Connection was killed.")
#define MSGJPN006		u8("Can't login to Firewall.")
#define MSGJPN007		u8("Can't connect to host %s.")
#define MSGJPN008		u8("Can't login.")
#define MSGJPN009		u8("Can't connect.")
#define MSGJPN010		u8("Firewall host not specified.")
#define MSGJPN011		u8("Host not specified.")
#define MSGJPN012		u8("MD5 used.")
#define MSGJPN013		u8("SHA-1 used.")
#define MSGJPN014		u8("MD4(S/KEY) used.")
#define MSGJPN015		u8("Can't process One-time Password.")
#define MSGJPN016		u8("Searching host %s.")
#define MSGJPN017		u8("Connecting %sto host %s (%s (%d)).")
#define MSGJPN018		u8("Connecting %sto host %s (%d).")
#define MSGJPN019		u8("Host %s not found.")
#define MSGJPN020		u8("Connecting %sto host %s (%d).")
#define MSGJPN021		u8("SOCKS server %s not found.")
#define MSGJPN022		u8("Connecting to SOCKS server %s (%d).")
#define MSGJPN023		u8("Can't connect to SOCKS server. (Err=%d)")
#define MSGJPN024		u8("Can't connect to SOCKS server. (Err=%d)")
#define MSGJPN025		u8("Connected.")
#define MSGJPN026		u8("Can't connected.")
#define MSGJPN027		u8("Can't create socket.")
#define MSGJPN028		u8("Can't connect to SOCKS server. (Err=%d)")
#define MSGJPN029		u8("Can't connect to SOCKS server. (Err=%d)")
#define MSGJPN030		u8("Can't create listen socket.")
#define MSGJPN031		u8("PORT command not accepted")
#define MSGJPN032		u8("Connection is cancelled by user.")
#define MSGJPN033		u8("Can't send SOCKS command. (Cmd = %04X)")
#define MSGJPN034		u8("Can't receive SOCKS5 reply.")
#define MSGJPN035		u8("Can't receive SOCKS4 reply.")
#define MSGJPN036		u8("SOCKS certification method not match.")
#define MSGJPN037		u8("Certification failed by SOCKS server.")
#define MSGJPN038		u8("Name")
#define MSGJPN039		u8("Date")
#define MSGJPN040		u8("Size")
#define MSGJPN041		u8("Ext")
#define MSGJPN042		u8("Name")
#define MSGJPN043		u8("Date")
#define MSGJPN044		u8("Size")
#define MSGJPN045		u8("Ext")
#define MSGJPN046		u8("Permissions")
#define MSGJPN047		u8("Owner")
#define MSGJPN048		u8("Can't read temporary file.")
#define MSGJPN049		u8("Failed to getting file list.")
#define MSGJPN050		u8("Find (Local)")
#define MSGJPN051		u8("Find (Host)")
#define MSGJPN052		u8("Dele: %s")
#define MSGJPN053		u8("Make: %s")
#define MSGJPN054		u8("Tran: %s")
#define MSGJPN055		u8("Dele: %s")
#define MSGJPN056		u8("Make: %s")
#define MSGJPN057		u8("Tran: %s")
#define MSGJPN058		u8("Transfer %d files.")
#define MSGJPN059		u8("No file to transmit.")
#define MSGJPN060		u8("Create %d folders.")
#define MSGJPN061		u8("No folder to create.")
#define MSGJPN062		u8("Delete %d files/folders.")
#define MSGJPN063		u8("No file/folder to delete.")
#define MSGJPN064		u8("Upload as")
#define MSGJPN065		u8("Download as")
#define MSGJPN066		u8("Delete (Local)")
#define MSGJPN067		u8("Delete (Host)")
#define MSGJPN068		u8("Rename (Local)")
#define MSGJPN069		u8("Rename (Host)")
#define MSGJPN070		u8("New Filder (Local)")
#define MSGJPN071		u8("New Folder (Host)")
#define MSGJPN072		u8("Change Current Folder (Local)")
#define MSGJPN073		u8("Change Current Folder (Host)")
#define MSGJPN074		u8("Calculate local file size.")
#define MSGJPN075		u8("Calculate host file size.")
#define MSGJPN076		u8("Local file size")
#define MSGJPN077		u8("Host file size")
#define MSGJPN078		u8("New Folder")
#define MSGJPN079		u8("New Folder")
#define MSGJPN080		u8("Delete Folder")
#define MSGJPN081		u8("Delete File")
#define MSGJPN082		u8("New Folder")
#define MSGJPN083		u8("Delete Folder")
#define MSGJPN084		u8("Delete File")
#define MSGJPN085		u8("Can't download named %s.")
#define MSGJPN086		u8("Download")
#define MSGJPN087		u8("File List")
#define MSGJPN088		u8("Skip")
#define MSGJPN089		u8("Skip file %s.")
#define MSGJPN090		u8("Command not accepted.")
#define MSGJPN091		u8("for download ")
#define MSGJPN092		u8("Command not accepted.")
#define MSGJPN093		u8("Can't get address.")
#define MSGJPN094		u8("Time out error.")
#define MSGJPN095		u8("Can't create file %s.")
#define MSGJPN096		u8("Disk full")
#define MSGJPN097		u8("Cancel to getting file list")
#define MSGJPN098		u8("File List")
#define MSGJPN099		u8("Download cancelled. (%d Sec. %d B/S).")
#define MSGJPN100		u8("Download cancelled.")
#define MSGJPN101		u8("Download file list successful. (%d Bytes)")
#define MSGJPN102		u8("Download successful. (%d Sec. %d B/S).")
#define MSGJPN103		u8("Download successful. (%d Bytes)")
#define MSGJPN104		u8("Upload")
#define MSGJPN105		u8("Can't read file %s.")
#define MSGJPN106		u8("Skip")
#define MSGJPN107		u8("File %s is skipped.")
#define MSGJPN108		u8("Command not accepted.")
#define MSGJPN109		u8("for upload ")
#define MSGJPN110		u8("Command not accepted.")
#define MSGJPN111		u8("Can't get address.")
#define MSGJPN112		u8("Can't open file %s.")
#define MSGJPN113		u8("Upload cancelled. (%d Sec. %d B/S).")
#define MSGJPN114		u8("Upload cancelled.")
#define MSGJPN115		u8("Upload successful. (%d Sec. %d B/S).")
#define MSGJPN116		u8("Upload successfil.")
#define MSGJPN117		u8("Finished")
#define MSGJPN118		u8("Cancelled")
#define MSGJPN119		u8("BINARY")
#define MSGJPN120		u8("ASCII")
#define MSGJPN121		u8("NONE")
#define MSGJPN122		u8("JIS")
#define MSGJPN123		u8("EUC")
#define MSGJPN124		u8("Delete(Local)")
#define MSGJPN125		u8("Delete(Host)")
#define MSGJPN126		u8("WS_FTP.INI")
#define MSGJPN127		u8("General")
#define MSGJPN128		u8("Advanced")
#define MSGJPN129		u8("Kanji Code")
#define MSGJPN130		u8("Dialup")
#define MSGJPN131		u8("Special")
#define MSGJPN132		u8("Host Setting")
#define MSGJPN133		u8("GMT%+02d:00")
#define MSGJPN134		u8("None")
#define MSGJPN135		u8("Auto")
#define MSGJPN136		u8("OTP MD4, S/KEY")
#define MSGJPN137		u8("OTP MD5")
#define MSGJPN138		u8("OTP SHA-1")
#define MSGJPN139		u8("Auto")
#define MSGJPN140		u8("ACOS")
#define MSGJPN141		u8("VAX VMS")
#define MSGJPN142		u8("IRMX")
#define MSGJPN143		u8("ACOS-4")
#define MSGJPN144		u8("Stratus")
#define MSGJPN145		u8("Can't change folder.")
#define MSGJPN146		u8("Can't create folder.")
#define MSGJPN147		u8("Can't delete folder.")
#define MSGJPN148		u8("Can't delete folder.")
#define MSGJPN149		u8("Can't delete file.")
#define MSGJPN150		u8("Can't delete file.")
#define MSGJPN151		u8("Can't rename file.")
#define MSGJPN152		u8("Temporary folder '%s' not found.")
#define MSGJPN153		u8("Folder '%s' is used.")
#define MSGJPN154		u8("Connect")
#define MSGJPN155		u8("Quick Connect")
#define MSGJPN156		u8("Disconnect")
#define MSGJPN157		u8("Download")
#define MSGJPN158		u8("Upload")
#define MSGJPN159		u8("Mirror Upload")
#define MSGJPN160		u8("Delete")
#define MSGJPN161		u8("Rename")
#define MSGJPN162		u8("New Folder")
#define MSGJPN163		u8("Parent Folder")
#define MSGJPN164		u8("Change Folder")
#define MSGJPN165		u8("ASCII Mode")
#define MSGJPN166		u8("BINARY Mode")
#define MSGJPN167		u8("Filename Depend")
#define MSGJPN168		u8("Refresh File List")
#define MSGJPN169		u8("List")
#define MSGJPN170		u8("Details")
#define MSGJPN171		u8("EUC Kanji Code")
#define MSGJPN172		u8("JIS Kanji Code")
#define MSGJPN173		u8("NO Kanji Conversin")
#define MSGJPN174		u8("Hankaku-Kana to Zenkaku")
#define MSGJPN175		u8("Sync. folder movement")
#define MSGJPN176		u8("Stop")
#define MSGJPN177		u8("Host profile '%s' not found.")
#define MSGJPN178		u8("Host profile not specified.")
#define MSGJPN179		u8("Host name is only used as an alternative to profile name.")
#define MSGJPN180		u8("Wrong Option '%s'.")
#define MSGJPN181		u8("Host name is only used as an alternative to profile name.")
#define MSGJPN182		u8("Failed to open viewer. (ERROR=%d)")
#define MSGJPN183		u8("JRE32.DLL none")
#define MSGJPN184		u8("JRE32.DLL Ver %x.%x (C) Kazuo Yamada-san")
#define MSGJPN185		u8("Select folder.")
#define MSGJPN186		u8("User")
#define MSGJPN187		u8("Transfer1")
#define MSGJPN188		u8("Transfer2")
#define MSGJPN189		u8("Transfer3")
#define MSGJPN190		u8("Mirroring")
#define MSGJPN191		u8("Operation")
#define MSGJPN192		u8("View")
#define MSGJPN193		u8("Connecting")
#define MSGJPN194		u8("Firewall")
#define MSGJPN195		u8("Tool")
#define MSGJPN196		u8("Sounds")
#define MSGJPN197		u8("Other")
#define MSGJPN198		u8("Option")
#define MSGJPN199		u8("Filename")
#define MSGJPN200		u8("Filename")
#define MSGJPN201		u8("Attr")
#define MSGJPN202		u8("Filename")
#define MSGJPN203		u8("Filename")
#define MSGJPN204		u8("FW user-> FW password-> SITE host")
#define MSGJPN205		u8("FW user-> FW password-> USER user@host")
#define MSGJPN206		u8("FW user-> FW password")
#define MSGJPN207		u8("USER user@host")
#define MSGJPN208		u8("OPEN host")
#define MSGJPN209		u8("SOCKS4")
#define MSGJPN210		u8("SOCKS5 (No certification)")
#define MSGJPN211		u8("SOCKS5 (User, Password certification)")
#define MSGJPN212		u8("None")
#define MSGJPN213		u8("Auto")
#define MSGJPN214		u8("OTP MD4,S/KEY")
#define MSGJPN215		u8("OTP MD5")
#define MSGJPN216		u8("OTP SHA-1")
#define MSGJPN217		u8("Select viewer")
#define MSGJPN218		u8("EXE file\0*.exe;*.com;*.bat\0All file(*.*)\0*\0")
#define MSGJPN219		u8("Wave file")
#define MSGJPN220		u8("Disconencting dialup.")
#define MSGJPN221		u8("Connecting dialup.")
#define MSGJPN222		u8("Can't use dialup. (RasDialDlg)")
#define MSGJPN223		u8("Connecting to %s...")
#define MSGJPN224		u8("Unknown error")
#define MSGJPN225		u8("Dialup connection")
#define MSGJPN226		u8("Open port...")
#define MSGJPN227		u8("Port opened.")
#define MSGJPN228		u8("Dialing...")
#define MSGJPN229		u8("Dialed.")
#define MSGJPN230		u8("All device connected.")
#define MSGJPN231		u8("Authenticating...")
#define MSGJPN232		u8("Authenticate retry...")
#define MSGJPN233		u8("Please change password.")
#define MSGJPN234		u8("Authenticated.")
#define MSGJPN235		u8("Connected")
#define MSGJPN236		u8("Disconnected.")
#define MSGJPN237		u8("Connecting...")
#define MSGJPN238		u8("Connecting to %s")
#define MSGJPN239		u8("# Do not edit this file.\n")
#define MSGJPN240		u8("Can't save to INI file")
#define MSGJPN241		u8("Failed transmit cause of timeout")
#define MSGJPN242		u8("Failed receive cause of timeout")
#define MSGJPN243		u8("Failed receive cause of timeout")
#define MSGJPN244		u8("Receive length error")
#define MSGJPN245		u8("Local")
#define MSGJPN246		u8("Host")
#define MSGJPN247		u8("Selected: %d (%s)")
#define MSGJPN248		u8("Local free: %s")
#define MSGJPN249		u8("Files in queue: %d")
#define MSGJPN250		u8("Receiving %s")
#define MSGJPN251		u8("Err: Seed")
#define MSGJPN252		u8("Err: Seed")
#define MSGJPN253		u8("Err: Sequence#")
#define MSGJPN254		u8("MS Shell Dlg")
#define MSGJPN255		u8("&Upload")
#define MSGJPN256		u8("U&pload As...")
#define MSGJPN257		u8("Up&load All")
#define MSGJPN258		u8("&Delete")
#define MSGJPN259		u8("&Rename...")
#define MSGJPN260		u8("&New Folder...")
#define MSGJPN261		u8("&File Size...")
#define MSGJPN262		u8("R&efresh File List")
#define MSGJPN263		u8("&Download")
#define MSGJPN264		u8("D&ownload As...")
#define MSGJPN265		u8("Do&wnliad as File")
#define MSGJPN266		u8("Dow&nload All")
#define MSGJPN267		u8("De&lete...")
#define MSGJPN268		u8("&Rename...")
#define MSGJPN269		u8("&Change Permission...")
#define MSGJPN270		u8("&New Folder...")
#define MSGJPN271		u8("Copy &URL to Clipboard")
#define MSGJPN272		u8("&File Size...")
#define MSGJPN273		u8("R&efresh File List")
#define MSGJPN274		u8("&Open")
#define MSGJPN275		u8("Open in %s (&%d)")
#define MSGJPN276		u8("WS_FTP.INI\0ws_ftp.ini\0All file(*.*)\0*\0")
#define MSGJPN277		u8("Wave file\0*.wav\0All file\0*\0")
#define MSGJPN278		u8("Reason: %s")
#define MSGJPN279		u8("Can't get Listen Socket")
#define MSGJPN280		u8("Can't get Data Socket")
#define MSGJPN281		u8("Can't connect with PASV mode")
#define MSGJPN282		u8("INI filename is not specified")
#define MSGJPN283		u8("INI file: ")
#define MSGJPN284		u8("http://sourceforge.jp/projects/ffftp/")
#define MSGJPN285		u8("Failed to execute Registory Editor.")
#define MSGJPN286		u8("Save Settings")
#define MSGJPN287		u8("Reg file\0*.reg\0All file\0*\0")
#define MSGJPN288		u8("INI file\0*.ini\0All file\0*\0")
#define MSGJPN289		u8("Agilent Logic analyzer")
#define MSGJPN290		u8("Reg file\0*.reg\0INI file\0*.ini\0All files\0*\0")
#define MSGJPN291		u8("Load Settings")
#define MSGJPN292		u8("Restart FFFTP to take effect.")
#define MSGJPN293		u8("File must be *.reg or *.ini.")
#define MSGJPN294		u8("USER FW user:FW password@host")
#define MSGJPN295		u8("ShibaSoku WL")
#define MSGJPN296		u8("This is a read-only file. Remove the read-only attribute?")
#define MSGJPN297		u8("%s is invalid path.\r\nFFFTP doesn't download this file.")
#define MSGJPN298		u8("Failed to initialize the OLE.")
#define MSGJPN299		u8("Master password is not specified in the command line")
#define MSGJPN300		u8("Default master password is chosen.\r\nSet your own master password in command line to prevent sniff of malwares")
#define MSGJPN301		u8("Master password is not for the current configuration. Configration will not be overwritten in this session.")
#define MSGJPN302		u8("Master password checker looks broken.")
#define MSGJPN303		u8("Master password has been changed.")
#define MSGJPN304		u8("Speecified master password is not correct.\r\nAre you sure you want to re-enter?\r\nNo memorized FTP password is available if you choose 'NO'")
#define MSGJPN305		u8("Shift_JIS")
#define MSGJPN306		u8("UTF-8")
#define MSGJPN307		u8("Shift_JIS Kanji Code")
#define MSGJPN308		u8("UTF-8 Kanji Code")
#define MSGJPN309		u8("Shift_JIS Kanji Code (Local)")
#define MSGJPN310		u8("EUC Kanji Code (Local)")
#define MSGJPN311		u8("JIS Kanji Code (Local)")
#define MSGJPN312		u8("UTF-8 Kanji Code (Local)")
#define MSGJPN313		u8("Encryption")
#define MSGJPN314		u8("Communication is not encrypted.\r\nPassword and other data may be intercepted by a third party.")
#define MSGJPN315		u8("Using FTP over Explicit SSL/TLS (FTPES).")
#define MSGJPN316		u8("Using FTP over Implicit SSL/TLS (FTPIS).")
#define MSGJPN317		u8("Using SSH FTP (SFTP).")
#define MSGJPN318		u8("OpenSSL is loaded.")
#define MSGJPN319		u8("OpenSSL is not installed.\r\nCommunication will not be encrypted.")
#define MSGJPN320		u8("Feature")
#define MSGJPN321		u8("Failed to get required functions to protect the process.")
#define MSGJPN322		u8("Debugger was detected.")
#define MSGJPN323		u8("Failed to unload untrustworthy DLLs.")
#define MSGJPN324		u8("Failed to hook required functions to protect the process.")
#define MSGJPN325		u8("New master passwords are not identical.")
#define MSGJPN326		u8("Choose 'Yes' if you trust this certificate and continue.\r\nCN is identical: %s\r\nVerified successfully: %s\r\n\r\n%s")
#define MSGJPN327		u8("Yes")
#define MSGJPN328		u8("No")
#define MSGJPN329		u8("UTF-8 BOM")
#define MSGJPN330		u8("UTF-8 BOM Kanji Code")
#define MSGJPN331		u8("UTF-8 BOM Kanji Code (Local)")
#define MSGJPN332		u8("Auto")
#define MSGJPN333		u8("TCP/IPv4")
#define MSGJPN334		u8("TCP/IPv6")
#define MSGJPN335		u8("Ask everytime")
#define MSGJPN336		u8("Overwrite all later")
#define MSGJPN337		u8("Resume all later")
#define MSGJPN338		u8("Skip all")
#if defined(HAVE_TANDEM)
#define MSGJPN2000		u8("NonStop Server")
#define MSGJPN2001		u8("OSS<->GUARDIAN Switch(&O)")
#endif
