#define _Tu8(text, u8text) (u8text)
#define MSGJPN001		_Tu8("Connection cancelled.", "Connection cancelled.")
#define MSGJPN002		_Tu8("Connection cancelled.", "Connection cancelled.")
#define MSGJPN003		_Tu8("\r\nReconnect.\r\n", "\r\nReconnect.\r\n")
#define MSGJPN004		_Tu8("Disconnect.", "Disconnect.")
#define MSGJPN005		_Tu8("Connection was killed.", "Connection was killed.")
#define MSGJPN006		_Tu8("Cannnot login to Firewall.", "Cannnot login to Firewall.")
#define MSGJPN007		_Tu8("Cannnot connect to host %s.", "Cannnot connect to host %s.")
#define MSGJPN008		_Tu8("Cannnot login.", "Cannnot login.")
#define MSGJPN009		_Tu8("Cannnot connect.", "Cannnot connect.")
#define MSGJPN010		_Tu8("Firewall host not specified.", "Firewall host not specified.")
#define MSGJPN011		_Tu8("Host not specified.", "Host not specified.")
#define MSGJPN012		_Tu8("MD5 used.", "MD5 used.")
#define MSGJPN013		_Tu8("SHA-1 used.", "SHA-1 used.")
#define MSGJPN014		_Tu8("MD4(S/KEY) used.", "MD4(S/KEY) used.")
#define MSGJPN015		_Tu8("Cannnot process One-time Password.", "Cannnot process One-time Password.")
#define MSGJPN016		_Tu8("Searching host %s. (%s)", "Searching host %s. (%s)")
#define MSGJPN017		_Tu8("Connecting %sto host %s (%s (%d)). (%s)", "Connecting %sto host %s (%s (%d)). (%s)")
#define MSGJPN018		_Tu8("Connecting %sto host %s (%d). (%s)", "Connecting %sto host %s (%d). (%s)")
#define MSGJPN019		_Tu8("Host %s not found. (%s)", "Host %s not found. (%s)")
#define MSGJPN020		_Tu8("Connecting %sto host %s (%d). (%s)", "Connecting %sto host %s (%d). (%s)")
#define MSGJPN021		_Tu8("SOCKS server %s not found. (%s)", "SOCKS server %s not found. (%s)")
#define MSGJPN022		_Tu8("Connecting to SOCKS server %s (%d). (%s)", "Connecting to SOCKS server %s (%d). (%s)")
#define MSGJPN023		_Tu8("Cannnot connect to SOCKS server. (Err=%d) (%s)", "Cannnot connect to SOCKS server. (Err=%d) (%s)")
#define MSGJPN024		_Tu8("Cannnot connect to SOCKS server. (Err=%d) (%s)", "Cannnot connect to SOCKS server. (Err=%d) (%s)")
#define MSGJPN025		_Tu8("Connected. (%s)", "Connected. (%s)")
#define MSGJPN026		_Tu8("Cannnot connected. (%s)", "Cannnot connected. (%s)")
#define MSGJPN027		_Tu8("Cannnot create socket. (%s)", "Cannnot create socket. (%s)")
#define MSGJPN028		_Tu8("Cannnot connect to SOCKS server. (Err=%d) (%s)", "Cannnot connect to SOCKS server. (Err=%d) (%s)")
#define MSGJPN029		_Tu8("Cannnot connect to SOCKS server. (Err=%d) (%s)", "Cannnot connect to SOCKS server. (Err=%d) (%s)")
#define MSGJPN030		_Tu8("Cannnot create listen socket. (%s)", "Cannnot create listen socket. (%s)")
#define MSGJPN031		_Tu8("PORT command not accepted. (%s)", "PORT command not accepted. (%s)")
#define MSGJPN032		_Tu8("Connection is cancelled by user.", "Connection is cancelled by user.")
#define MSGJPN033		_Tu8("Cannnot send SOCKS command. (Cmd = %04X)", "Cannnot send SOCKS command. (Cmd = %04X)")
#define MSGJPN034		_Tu8("Cannnot receive SOCKS5 reply.", "Cannnot receive SOCKS5 reply.")
#define MSGJPN035		_Tu8("Cannnot receive SOCKS4 reply.", "Cannnot receive SOCKS4 reply.")
#define MSGJPN036		_Tu8("SOCKS certification method not match.", "SOCKS certification method not match.")
#define MSGJPN037		_Tu8("Certification failed by SOCKS server.", "Certification failed by SOCKS server.")
#define MSGJPN038		_Tu8("Name", "Name")
#define MSGJPN039		_Tu8("Date", "Date")
#define MSGJPN040		_Tu8("Size", "Size")
#define MSGJPN041		_Tu8("Ext", "Ext")
#define MSGJPN042		_Tu8("Name", "Name")
#define MSGJPN043		_Tu8("Date", "Date")
#define MSGJPN044		_Tu8("Size", "Size")
#define MSGJPN045		_Tu8("Ext", "Ext")
#define MSGJPN046		_Tu8("Permissions", "Permissions")
#define MSGJPN047		_Tu8("Owner", "Owner")
#define MSGJPN048		_Tu8("Cannnot read temporary file.", "Cannnot read temporary file.")
#define MSGJPN049		_Tu8("Failed to getting file list.", "Failed to getting file list.")
#define MSGJPN050		_Tu8("Find (Local)", "Find (Local)")
#define MSGJPN051		_Tu8("Find (Host)", "Find (Host)")
#define MSGJPN052		_Tu8("Dele: %s", "Dele: %s")
#define MSGJPN053		_Tu8("Make: %s", "Make: %s")
#define MSGJPN054		_Tu8("Tran: %s", "Tran: %s")
#define MSGJPN055		_Tu8("Dele: %s", "Dele: %s")
#define MSGJPN056		_Tu8("Make: %s", "Make: %s")
#define MSGJPN057		_Tu8("Tran: %s", "Tran: %s")
#define MSGJPN058		_Tu8("Transfer %d files.", "Transfer %d files.")
#define MSGJPN059		_Tu8("No file to transmit.", "No file to transmit.")
#define MSGJPN060		_Tu8("Create %d folders.", "Create %d folders.")
#define MSGJPN061		_Tu8("No folder to create.", "No folder to create.")
#define MSGJPN062		_Tu8("Delete %d files/folders.", "Delete %d files/folders.")
#define MSGJPN063		_Tu8("No file/folder to delete.", "No file/folder to delete.")
#define MSGJPN064		_Tu8("Upload as", "Upload as")
#define MSGJPN065		_Tu8("Download as", "Download as")
#define MSGJPN066		_Tu8("Delete (Local)", "Delete (Local)")
#define MSGJPN067		_Tu8("Delete (Host)", "Delete (Host)")
#define MSGJPN068		_Tu8("Rename (Local)", "Rename (Local)")
#define MSGJPN069		_Tu8("Rename (Host)", "Rename (Host)")
#define MSGJPN070		_Tu8("New Filder (Local)", "New Filder (Local)")
#define MSGJPN071		_Tu8("New Folder (Host)", "New Folder (Host)")
#define MSGJPN072		_Tu8("Change Current Folder (Local)", "Change Current Folder (Local)")
#define MSGJPN073		_Tu8("Change Current Folder (Host)", "Change Current Folder (Host)")
#define MSGJPN074		_Tu8("Calculate local file size.", "Calculate local file size.")
#define MSGJPN075		_Tu8("Calculate host file size.", "Calculate host file size.")
#define MSGJPN076		_Tu8("Local file size", "Local file size")
#define MSGJPN077		_Tu8("Host file size", "Host file size")
#define MSGJPN078		_Tu8("New Folder", "New Folder")
#define MSGJPN079		_Tu8("New Folder", "New Folder")
#define MSGJPN080		_Tu8("Delete Folder", "Delete Folder")
#define MSGJPN081		_Tu8("Delete File", "Delete File")
#define MSGJPN082		_Tu8("New Folder", "New Folder")
#define MSGJPN083		_Tu8("Delete Folder", "Delete Folder")
#define MSGJPN084		_Tu8("Delete File", "Delete File")
#define MSGJPN085		_Tu8("Cannnot download named %s.", "Cannnot download named %s.")
#define MSGJPN086		_Tu8("Download", "Download")
#define MSGJPN087		_Tu8("File List", "File List")
#define MSGJPN088		_Tu8("Skip", "Skip")
#define MSGJPN089		_Tu8("Skip file %s.", "Skip file %s.")
#define MSGJPN090		_Tu8("Command not accepted.", "Command not accepted.")
#define MSGJPN091		_Tu8("for download ", "for download ")
#define MSGJPN092		_Tu8("Command not accepted.", "Command not accepted.")
#define MSGJPN093		_Tu8("Cannnot get address.", "Cannnot get address.")
#define MSGJPN094		_Tu8("Time out error.", "Time out error.")
#define MSGJPN095		_Tu8("Cannnot create file %s.", "Cannnot create file %s.")
#define MSGJPN096		_Tu8("Disk full", "Disk full")
#define MSGJPN097		_Tu8("Cancel to getting file list", "Cancel to getting file list")
#define MSGJPN098		_Tu8("File List", "File List")
#define MSGJPN099		_Tu8("Download cancelled. (%lld Sec. %lld B/S).", "Download cancelled. (%lld Sec. %lld B/S).")
#define MSGJPN100		_Tu8("Download cancelled.", "Download cancelled.")
#define MSGJPN101		_Tu8("Download file list successful. (%lld Bytes)", "Download file list successful. (%lld Bytes)")
#define MSGJPN102		_Tu8("Download successful. (%d Sec. %d B/S).", "Download successful. (%d Sec. %d B/S).")
#define MSGJPN103		_Tu8("Download successful. (%lld Bytes)", "Download successful. (%lld Bytes)")
#define MSGJPN104		_Tu8("Upload", "Upload")
#define MSGJPN105		_Tu8("Cannnot read file %s.", "Cannnot read file %s.")
#define MSGJPN106		_Tu8("Skip", "Skip")
#define MSGJPN107		_Tu8("File %s is skipped.", "File %s is skipped.")
#define MSGJPN108		_Tu8("Command not accepted.", "Command not accepted.")
#define MSGJPN109		_Tu8("for upload ", "for upload ")
#define MSGJPN110		_Tu8("Command not accepted.", "Command not accepted.")
#define MSGJPN111		_Tu8("Cannnot get address.", "Cannnot get address.")
#define MSGJPN112		_Tu8("Cannnot open file %s.", "Cannnot open file %s.")
#define MSGJPN113		_Tu8("Upload cancelled. (%lld Sec. %lld B/S).", "Upload cancelled. (%lld Sec. %lld B/S).")
#define MSGJPN114		_Tu8("Upload cancelled.", "Upload cancelled.")
#define MSGJPN115		_Tu8("Upload successful. (%d Sec. %d B/S).", "Upload successful. (%d Sec. %d B/S).")
#define MSGJPN116		_Tu8("Upload successfil.", "Upload successfil.")
#define MSGJPN117		_Tu8("Finished", "Finished")
#define MSGJPN118		_Tu8("Cancelled", "Cancelled")
#define MSGJPN119		_Tu8("BINARY", "BINARY")
#define MSGJPN120		_Tu8("ASCII", "ASCII")
#define MSGJPN121		_Tu8("NONE", "NONE")
#define MSGJPN122		_Tu8("JIS", "JIS")
#define MSGJPN123		_Tu8("EUC", "EUC")
#define MSGJPN124		_Tu8("Delete(Local)", "Delete(Local)")
#define MSGJPN125		_Tu8("Delete(Host)", "Delete(Host)")
#define MSGJPN126		_Tu8("WS_FTP.INI", "WS_FTP.INI")
#define MSGJPN127		_Tu8("General", "General")
#define MSGJPN128		_Tu8("Advanced", "Advanced")
#define MSGJPN129		_Tu8("Kanji Code", "Kanji Code")
#define MSGJPN130		_Tu8("Dialup", "Dialup")
#define MSGJPN131		_Tu8("Special", "Special")
#define MSGJPN132		_Tu8("Host Setting", "Host Setting")
#define MSGJPN133		_Tu8("GMT%+02d:00", "GMT%+02d:00")
#define MSGJPN134		_Tu8("None", "None")
#define MSGJPN135		_Tu8("Auto", "Auto")
#define MSGJPN136		_Tu8("OTP MD4, S/KEY", "OTP MD4, S/KEY")
#define MSGJPN137		_Tu8("OTP MD5", "OTP MD5")
#define MSGJPN138		_Tu8("OTP SHA-1", "OTP SHA-1")
#define MSGJPN139		_Tu8("Auto", "Auto")
#define MSGJPN140		_Tu8("ACOS", "ACOS")
#define MSGJPN141		_Tu8("VAX VMS", "VAX VMS")
#define MSGJPN142		_Tu8("IRMX", "IRMX")
#define MSGJPN143		_Tu8("ACOS-4", "ACOS-4")
#define MSGJPN144		_Tu8("Stratus", "Stratus")
#define MSGJPN145		_Tu8("Cannnot change folder.", "Cannnot change folder.")
#define MSGJPN146		_Tu8("Cannnot create folder.", "Cannnot create folder.")
#define MSGJPN147		_Tu8("Cannnot delete folder.", "Cannnot delete folder.")
#define MSGJPN148		_Tu8("Cannnot delete folder.", "Cannnot delete folder.")
#define MSGJPN149		_Tu8("Cannnot delete file.", "Cannnot delete file.")
#define MSGJPN150		_Tu8("Cannnot delete file.", "Cannnot delete file.")
#define MSGJPN151		_Tu8("Cannnot rename file.", "Cannnot rename file.")
#define MSGJPN152		_Tu8("Temporary folder '%s' not found.", "Temporary folder '%s' not found.")
#define MSGJPN153		_Tu8("Folder '%s' is used.", "Folder '%s' is used.")
#define MSGJPN154		_Tu8("Connect", "Connect")
#define MSGJPN155		_Tu8("Quick Connect", "Quick Connect")
#define MSGJPN156		_Tu8("Disconnect", "Disconnect")
#define MSGJPN157		_Tu8("Download", "Download")
#define MSGJPN158		_Tu8("Upload", "Upload")
#define MSGJPN159		_Tu8("Mirror Upload", "Mirror Upload")
#define MSGJPN160		_Tu8("Delete", "Delete")
#define MSGJPN161		_Tu8("Rename", "Rename")
#define MSGJPN162		_Tu8("New Folder", "New Folder")
#define MSGJPN163		_Tu8("Parent Folder", "Parent Folder")
#define MSGJPN164		_Tu8("Change Folder", "Change Folder")
#define MSGJPN165		_Tu8("ASCII Mode", "ASCII Mode")
#define MSGJPN166		_Tu8("BINARY Mode", "BINARY Mode")
#define MSGJPN167		_Tu8("Filename Depend", "Filename Depend")
#define MSGJPN168		_Tu8("Refresh File List", "Refresh File List")
#define MSGJPN169		_Tu8("List", "List")
#define MSGJPN170		_Tu8("Details", "Details")
#define MSGJPN171		_Tu8("EUC Kanji Code", "EUC Kanji Code")
#define MSGJPN172		_Tu8("JIS Kanji Code", "JIS Kanji Code")
#define MSGJPN173		_Tu8("NO Kanji Conversin", "NO Kanji Conversin")
#define MSGJPN174		_Tu8("Hankaku-Kana to Zenkaku", "Hankaku-Kana to Zenkaku")
#define MSGJPN175		_Tu8("Sync. folder movement", "Sync. folder movement")
#define MSGJPN176		_Tu8("Stop", "Stop")
#define MSGJPN177		_Tu8("Host profile '%s' not found.", "Host profile '%s' not found.")
#define MSGJPN178		_Tu8("Host profile not specified.", "Host profile not specified.")
#define MSGJPN179		_Tu8("Host name is only used as an alternative to profile name.", "Host name is only used as an alternative to profile name.")
#define MSGJPN180		_Tu8("Wrong Option '%s'.", "Wrong Option '%s'.")
#define MSGJPN181		_Tu8("Host name is only used as an alternative to profile name.", "Host name is only used as an alternative to profile name.")
#define MSGJPN182		_Tu8("Failed to open viewer. (ERROR=%d)", "Failed to open viewer. (ERROR=%d)")
#define MSGJPN183		_Tu8("JRE32.DLL none", "JRE32.DLL none")
#define MSGJPN184		_Tu8("JRE32.DLL Ver %x.%x (C) Kazuo Yamada-san", "JRE32.DLL Ver %x.%x (C) Kazuo Yamada-san")
#define MSGJPN185		_Tu8("Select folder.", "Select folder.")
#define MSGJPN186		_Tu8("User", "User")
#define MSGJPN187		_Tu8("Transfer1", "Transfer1")
#define MSGJPN188		_Tu8("Transfer2", "Transfer2")
#define MSGJPN189		_Tu8("Transfer3", "Transfer3")
#define MSGJPN190		_Tu8("Mirroring", "Mirroring")
#define MSGJPN191		_Tu8("Operation", "Operation")
#define MSGJPN192		_Tu8("View1", "View1")
#define MSGJPN193		_Tu8("Connecting", "Connecting")
#define MSGJPN194		_Tu8("Firewall", "Firewall")
#define MSGJPN195		_Tu8("Tool", "Tool")
#define MSGJPN196		_Tu8("Sounds", "Sounds")
#define MSGJPN197		_Tu8("Other", "Other")
#define MSGJPN198		_Tu8("Option", "Option")
#define MSGJPN199		_Tu8("Filename", "Filename")
#define MSGJPN200		_Tu8("Filename", "Filename")
#define MSGJPN201		_Tu8("Attr", "Attr")
#define MSGJPN202		_Tu8("Filename", "Filename")
#define MSGJPN203		_Tu8("Filename", "Filename")
#define MSGJPN204		_Tu8("FW user-> FW password-> SITE host", "FW user-> FW password-> SITE host")
#define MSGJPN205		_Tu8("FW user-> FW password-> USER user@host", "FW user-> FW password-> USER user@host")
#define MSGJPN206		_Tu8("FW user-> FW password", "FW user-> FW password")
#define MSGJPN207		_Tu8("USER user@host", "USER user@host")
#define MSGJPN208		_Tu8("OPEN host", "OPEN host")
#define MSGJPN209		_Tu8("SOCKS4", "SOCKS4")
#define MSGJPN210		_Tu8("SOCKS5 (No certification)", "SOCKS5 (No certification)")
#define MSGJPN211		_Tu8("SOCKS5 (User, Password certification)", "SOCKS5 (User, Password certification)")
#define MSGJPN212		_Tu8("None", "None")
#define MSGJPN213		_Tu8("Auto", "Auto")
#define MSGJPN214		_Tu8("OTP MD4,S/KEY", "OTP MD4,S/KEY")
#define MSGJPN215		_Tu8("OTP MD5", "OTP MD5")
#define MSGJPN216		_Tu8("OTP SHA-1", "OTP SHA-1")
#define MSGJPN217		_Tu8("Select viewer", "Select viewer")
#define MSGJPN218		_Tu8("EXE file\0*.exe;*.com;*.bat\0All file(*.*)\0*\0", "EXE file\0*.exe;*.com;*.bat\0All file(*.*)\0*\0")
#define MSGJPN219		_Tu8("Wave file", "Wave file")
#define MSGJPN220		_Tu8("Disconencting dialup.", "Disconencting dialup.")
#define MSGJPN221		_Tu8("Connecting dialup.", "Connecting dialup.")
#define MSGJPN222		_Tu8("Cannnot use dialup. (RasDialDlg)", "Cannnot use dialup. (RasDialDlg)")
#define MSGJPN223		_Tu8("Connecting to %s...", "Connecting to %s...")
#define MSGJPN224		_Tu8("Unknown error", "Unknown error")
#define MSGJPN225		_Tu8("Dialup connection", "Dialup connection")
#define MSGJPN226		_Tu8("Open port...", "Open port...")
#define MSGJPN227		_Tu8("Port opened.", "Port opened.")
#define MSGJPN228		_Tu8("Dialing...", "Dialing...")
#define MSGJPN229		_Tu8("Dialed.", "Dialed.")
#define MSGJPN230		_Tu8("All device connected.", "All device connected.")
#define MSGJPN231		_Tu8("Authenticating...", "Authenticating...")
#define MSGJPN232		_Tu8("Authenticate retry...", "Authenticate retry...")
#define MSGJPN233		_Tu8("Please change password.", "Please change password.")
#define MSGJPN234		_Tu8("Authenticated.", "Authenticated.")
#define MSGJPN235		_Tu8("Connected", "Connected")
#define MSGJPN236		_Tu8("Disconnected.", "Disconnected.")
#define MSGJPN237		_Tu8("Connecting...", "Connecting...")
#define MSGJPN238		_Tu8("Connecting to %s", "Connecting to %s")
#define MSGJPN239		_Tu8("# Do not edit this file.\n", "# Do not edit this file.\n")
#define MSGJPN240		_Tu8("Cannnot save to INI file", "Cannnot save to INI file")
#define MSGJPN241		_Tu8("Failed transmit cause of timeout", "Failed transmit cause of timeout")
#define MSGJPN242		_Tu8("Failed receive cause of timeout", "Failed receive cause of timeout")
#define MSGJPN243		_Tu8("Failed receive cause of timeout", "Failed receive cause of timeout")
#define MSGJPN244		_Tu8("Receive length error", "Receive length error")
#define MSGJPN245		_Tu8("Local", "Local")
#define MSGJPN246		_Tu8("Host", "Host")
#define MSGJPN247		_Tu8("Selected: %d (%s)", "Selected: %d (%s)")
#define MSGJPN248		_Tu8("Local free: %s", "Local free: %s")
#define MSGJPN249		_Tu8("Files in queue: %d", "Files in queue: %d")
#define MSGJPN250		_Tu8("Receiving %s", "Receiving %s")
#define MSGJPN251		_Tu8("Err: Seed", "Err: Seed")
#define MSGJPN252		_Tu8("Err: Seed", "Err: Seed")
#define MSGJPN253		_Tu8("Err: Sequence#", "Err: Sequence#")
#define MSGJPN254		_Tu8("MS Shell Dlg", "MS Shell Dlg")
#define MSGJPN255		_Tu8("&Upload", "&Upload")
#define MSGJPN256		_Tu8("U&pload As...", "U&pload As...")
#define MSGJPN257		_Tu8("Up&load All", "Up&load All")
#define MSGJPN258		_Tu8("&Delete", "&Delete")
#define MSGJPN259		_Tu8("&Rename...", "&Rename...")
#define MSGJPN260		_Tu8("&New Folder...", "&New Folder...")
#define MSGJPN261		_Tu8("&File Size...", "&File Size...")
#define MSGJPN262		_Tu8("R&efresh File List", "R&efresh File List")
#define MSGJPN263		_Tu8("&Download", "&Download")
#define MSGJPN264		_Tu8("D&ownload As...", "D&ownload As...")
#define MSGJPN265		_Tu8("Do&wnliad as File", "Do&wnliad as File")
#define MSGJPN266		_Tu8("Dow&nload All", "Dow&nload All")
#define MSGJPN267		_Tu8("De&lete...", "De&lete...")
#define MSGJPN268		_Tu8("&Rename...", "&Rename...")
#define MSGJPN269		_Tu8("&Change Permission...", "&Change Permission...")
#define MSGJPN270		_Tu8("&New Folder...", "&New Folder...")
#define MSGJPN271		_Tu8("Copy &URL to Clipboard", "Copy &URL to Clipboard")
#define MSGJPN272		_Tu8("&File Size...", "&File Size...")
#define MSGJPN273		_Tu8("R&efresh File List", "R&efresh File List")
#define MSGJPN274		_Tu8("&Open", "&Open")
#define MSGJPN275		_Tu8("Open in %s (&%d)", "Open in %s (&%d)")
#define MSGJPN276		_Tu8("WS_FTP.INI\0ws_ftp.ini\0All file(*.*)\0*\0", "WS_FTP.INI\0ws_ftp.ini\0All file(*.*)\0*\0")
#define MSGJPN277		_Tu8("Wave file\0*.wav\0All file\0*\0", "Wave file\0*.wav\0All file\0*\0")
#define MSGJPN278		_Tu8("Reason: %s", "Reason: %s")
#define MSGJPN279		_Tu8("Cannnot get Listen Socket", "Cannnot get Listen Socket")
#define MSGJPN280		_Tu8("Cannnot get Data Socket", "Cannnot get Data Socket")
#define MSGJPN281		_Tu8("Cannnot connect with PASV mode", "Cannnot connect with PASV mode")
#define MSGJPN282		_Tu8("INI filename is not specified", "INI filename is not specified")
#define MSGJPN283		_Tu8("INI file: ", "INI file: ")
#define MSGJPN284		_Tu8("http://osdn.jp/projects/ffftp/", "http://osdn.jp/projects/ffftp/")
#define MSGJPN285		_Tu8("Failed to execute Registory Editor.", "Failed to execute Registory Editor.")
#define MSGJPN286		_Tu8("Save Settings", "Save Settings")
#define MSGJPN287		_Tu8("Reg file\0*.reg\0All file\0*\0", "Reg file\0*.reg\0All file\0*\0")
#define MSGJPN288		_Tu8("INI file\0*.ini\0All file\0*\0", "INI file\0*.ini\0All file\0*\0")
#define MSGJPN289		_Tu8("Agilent Logic analyzer", "Agilent Logic analyzer")
#define MSGJPN290		_Tu8("Reg file\0*.reg\0INI file\0*.ini\0All files\0*\0", "Reg file\0*.reg\0INI file\0*.ini\0All files\0*\0")
#define MSGJPN291		_Tu8("Load Settings", "Load Settings")
#define MSGJPN292		_Tu8("Restart FFFTP to take effect.", "Restart FFFTP to take effect.")
#define MSGJPN293		_Tu8("File must be *.reg or *.ini.", "File must be *.reg or *.ini.")
#define MSGJPN294		_Tu8("USER FW user:FW password@host", "USER FW user:FW password@host")
#define MSGJPN295		_Tu8("ShibaSoku WL", "ShibaSoku WL")
#define MSGJPN296		_Tu8("This is a read-only file. Remove the read-only attribute?", "This is a read-only file. Remove the read-only attribute?")
#define MSGJPN297		_Tu8("%s is invalid path.\r\nFFFTP doesn't download this file.", "%s is invalid path.\r\nFFFTP doesn't download this file.")
#define MSGJPN298		_Tu8("Failed to initialize the OLE.", "Failed to initialize the OLE.")
#define MSGJPN299		_Tu8("Master password is not specified in the command line", "Master password is not specified in the command line")
#define MSGJPN300		_Tu8("Default master password is chosen.\r\nSet your own master password in command line to prevent sniff of malwares", "Default master password is chosen.\r\nSet your own master password in command line to prevent sniff of malwares")
#define MSGJPN301		_Tu8("Master password is not for the current configuration. Configration will not be overwritten in this session.", "Master password is not for the current configuration. Configration will not be overwritten in this session.")
#define MSGJPN302		_Tu8("Master password checker looks broken.", "Master password checker looks broken.")
#define MSGJPN303		_Tu8("Master password has been changed.", "Master password has been changed.")
#define MSGJPN304		_Tu8("Speecified master password is not correct.\r\nAre you sure you want to re-enter?\r\nNo memorized FTP password is available if you choose 'NO'", "Speecified master password is not correct.\r\nAre you sure you want to re-enter?\r\nNo memorized FTP password is available if you choose 'NO'")
#define MSGJPN305		_Tu8("Shift_JIS", "Shift_JIS")
#define MSGJPN306		_Tu8("UTF-8", "UTF-8")
#define MSGJPN307		_Tu8("Shift_JIS Kanji Code", "Shift_JIS Kanji Code")
#define MSGJPN308		_Tu8("UTF-8 Kanji Code", "UTF-8 Kanji Code")
#define MSGJPN309		_Tu8("Shift_JIS Kanji Code (Local)", "Shift_JIS Kanji Code (Local)")
#define MSGJPN310		_Tu8("EUC Kanji Code (Local)", "EUC Kanji Code (Local)")
#define MSGJPN311		_Tu8("JIS Kanji Code (Local)", "JIS Kanji Code (Local)")
#define MSGJPN312		_Tu8("UTF-8 Kanji Code (Local)", "UTF-8 Kanji Code (Local)")
#define MSGJPN313		_Tu8("Encryption", "Encryption")
#define MSGJPN314		_Tu8("Communication is not encrypted.\r\nPassword and other data may be intercepted by a third party.", "Communication is not encrypted.\r\nPassword and other data may be intercepted by a third party.")
#define MSGJPN315		_Tu8("Using FTP over Explicit SSL/TLS (FTPES).", "Using FTP over Explicit SSL/TLS (FTPES).")
#define MSGJPN316		_Tu8("Using FTP over Implicit SSL/TLS (FTPIS).", "Using FTP over Implicit SSL/TLS (FTPIS).")
#define MSGJPN317		_Tu8("Using SSH FTP (SFTP).", "Using SSH FTP (SFTP).")
#define MSGJPN318		_Tu8("OpenSSL is loaded.", "OpenSSL is loaded.")
#define MSGJPN319		_Tu8("OpenSSL is not installed.\r\nCommunication will not be encrypted.", "OpenSSL is not installed.\r\nCommunication will not be encrypted.")
#define MSGJPN320		_Tu8("Feature", "Feature")
#define MSGJPN321		_Tu8("Failed to get required functions to protect the process.", "Failed to get required functions to protect the process.")
#define MSGJPN322		_Tu8("Debugger was detected.", "Debugger was detected.")
#define MSGJPN323		_Tu8("Failed to unload untrustworthy DLLs.", "Failed to unload untrustworthy DLLs.")
#define MSGJPN324		_Tu8("Failed to hook required functions to protect the process.", "Failed to hook required functions to protect the process.")
#define MSGJPN325		_Tu8("New master passwords are not identical.", "New master passwords are not identical.")
#define MSGJPN326		_Tu8("Choose 'Yes' if you trust this certificate and continue.\r\nCN is identical: %s\r\nVerified successfully: %s\r\n\r\n%s", "Choose 'Yes' if you trust this certificate and continue.\r\nCN is identical: %s\r\nVerified successfully: %s\r\n\r\n%s")
#define MSGJPN327		_Tu8("Yes", "Yes")
#define MSGJPN328		_Tu8("No", "No")
#define MSGJPN329		_Tu8("UTF-8 BOM", "UTF-8 BOM")
#define MSGJPN330		_Tu8("UTF-8 BOM Kanji Code", "UTF-8 BOM Kanji Code")
#define MSGJPN331		_Tu8("UTF-8 BOM Kanji Code (Local)", "UTF-8 BOM Kanji Code (Local)")
#define MSGJPN332		_Tu8("Auto", "Auto")
#define MSGJPN333		_Tu8("TCP/IPv4", "TCP/IPv4")
#define MSGJPN334		_Tu8("TCP/IPv6", "TCP/IPv6")
#define MSGJPN335		_Tu8("Ask everytime", "Ask everytime")
#define MSGJPN336		_Tu8("Overwrite all later", "Overwrite all later")
#define MSGJPN337		_Tu8("Resume all later", "Resume all later")
#define MSGJPN338		_Tu8("Skip all", "Skip all")
#define MSGJPN339		_Tu8("Transfer4", "Transfer4")
#define MSGJPN340		_Tu8("View2", "View2")
#define MSGJPN341		_Tu8("Enable or disable stateful FTP filtering of Windows Firewall.\nIt works only on Windows Vista or later.\nEnabling or disabling may improve communication conditions.\nChoose 'Yes' to enable or 'No' to disable it.", "Enable or disable stateful FTP filtering of Windows Firewall.\nIt works only on Windows Vista or later.\nEnabling or disabling may improve communication conditions.\nChoose 'Yes' to enable or 'No' to disable it.")
#define MSGJPN342		_Tu8("Failed to turn on/off stateful FTP filtering.", "Failed to turn on/off stateful FTP filtering.")
#define MSGJPN343		_Tu8("Determination result of the filename Kanji code is %s.", "Determination result of the filename Kanji code is %s.")
#define MSGJPN344		_Tu8("Failed to determine the filename Kanji code.", "Failed to determine the filename Kanji code.")
#define MSGJPN345		_Tu8("Shift_JIS", "Shift_JIS")
#define MSGJPN346		_Tu8("JIS", "JIS")
#define MSGJPN347		_Tu8("EUC", "EUC")
#define MSGJPN348		_Tu8("UTF-8", "UTF-8")
#define MSGJPN349		_Tu8("UTF-8 HFS+", "UTF-8 HFS+")
#define MSGJPN350		_Tu8("The settings of a newer version are detected.\nThe settings may not be read correctly, or they will be changed when they are overwritten for this version.\nChoose 'Yes' to overwrite settings for this version.\nChoose 'No' to save settings to the INI file.\nChoose 'Cancel' to load settings as read only.", "The settings of a newer version are detected.\nThe settings may not be read correctly, or they will be changed when they are overwritten for this version.\nChoose 'Yes' to overwrite settings for this version.\nChoose 'No' to save settings to the INI file.\nChoose 'Cancel' to load settings as read only.")
#define MSGJPN351		_Tu8("Warning: No encryption", "Warning: No encryption")
#define MSGJPN352		_Tu8("Encrypted: FTPES", "Encrypted: FTPES")
#define MSGJPN353		_Tu8("Encrypted: FTPIS", "Encrypted: FTPIS")
#define MSGJPN354		_Tu8("Encrypted: SFTP", "Encrypted: SFTP")
#define MSGJPN355		_Tu8("Move to &parent folder...", "Move to &parent folder...")
#define MSGJPN356		_Tu8("XML file\0*.xml\0All file\0*\0", "XML file\0*.xml\0All file\0*\0")
#define MSGJPN357		_Tu8("Failed to export the settings.\nPlease change saving path or format.", "Failed to export the settings.\nPlease change saving path or format.")
#define MSGJPN358		_Tu8("Software update has been completed.\nA backup copy of the previous version is in the following location.\n%s", "Software update has been completed.\nA backup copy of the previous version is in the following location.\n%s")
#define MSGJPN359		_Tu8("Failed to update the software.\nPlease get the latest version from our web site and update it manually.", "Failed to update the software.\nPlease get the latest version from our web site and update it manually.")
#define MSGJPN360		_Tu8("Updates", "Updates")
#define MSGJPN361		_Tu8("There is a new version.\n\nCurrent version: %s\nNew version: %s\n%s\n\nIt takes a few minutes to download the updates.\nDo you want to update now?\n", "There is a new version.\n\nCurrent version: %s\nNew version: %s\n%s\n\nIt takes a few minutes to download the updates.\nDo you want to update now?\n")
#define MSGJPN362		_Tu8("Failed to update the software.\nCannot connect to the server or the data is corrupted.", "Failed to update the software.\nCannot connect to the server or the data is corrupted.")
#define MSGJPN363		_Tu8("Your version is already up-to-date.", "Your version is already up-to-date.")
#define MSGJPN364		_Tu8("Preparing for the software update has been completed.\nIt will be applied on exit.", "Preparing for the software update has been completed.\nIt will be applied on exit.")
#define MSGJPN365		_Tu8("The all settings will be lost after loading an INI file newly created with this feature into WinSCP.\nPlease choose an existing WinSCP.ini if you already use WinSCP and want to migrate hosts settings only.", "The all settings will be lost after loading an INI file newly created with this feature into WinSCP.\nPlease choose an existing WinSCP.ini if you already use WinSCP and want to migrate hosts settings only.")
#if defined(HAVE_TANDEM)
#define MSGJPN2000		_Tu8("NonStop Server", "NonStop Server")
#define MSGJPN2001		_Tu8("OSS<->GUARDIAN Switch(&O)", "OSS<->GUARDIAN Switch(&O)")
#endif
