#define MSGJPN001		"Connection cancelled."
#define MSGJPN002		"Connection cancelled."
#define MSGJPN003		"\r\nReconnect.\r\n"
#define MSGJPN004		"Disconnect."
#define MSGJPN005		"Connection was killed."
#define MSGJPN006		"Can't login to Firewall."
#define MSGJPN007		"Can't connect to host %s."
#define MSGJPN008		"Can't login."
#define MSGJPN009		"Can't connect."
#define MSGJPN010		"Firewall host not specified."
#define MSGJPN011		"Host not specified."
#define MSGJPN012		"MD5 used."
#define MSGJPN013		"SHA-1 used."
#define MSGJPN014		"MD4(S/KEY) used."
#define MSGJPN015		"Can't process One-time Password."
#define MSGJPN016		"Searching host %s."
#define MSGJPN017		"Connecting %sto host %s (%s (%d))."
#define MSGJPN018		"Connecting %sto host %s (%d)."
#define MSGJPN019		"Host %s not found."
#define MSGJPN020		"Connecting %sto host %s (%d)."
#define MSGJPN021		"SOCKS server %s not found."
#define MSGJPN022		"Connecting to SOCKS server %s (%d)."
#define MSGJPN023		"Can't connect to SOCKS server. (Err=%d)"
#define MSGJPN024		"Can't connect to SOCKS server. (Err=%d)"
#define MSGJPN025		"Connected."
#define MSGJPN026		"Can't connected."
#define MSGJPN027		"Can't create socket."
#define MSGJPN028		"Can't connect to SOCKS server. (Err=%d)"
#define MSGJPN029		"Can't connect to SOCKS server. (Err=%d)"
#define MSGJPN030		"Can't create listen socket."
#define MSGJPN031		"PORT command not accepted"
#define MSGJPN032		"Connection is cancelled by user."
#define MSGJPN033		"Can't send SOCKS command. (Cmd = %04X)"
#define MSGJPN034		"Can't receive SOCKS5 reply."
#define MSGJPN035		"Can't receive SOCKS4 reply."
#define MSGJPN036		"SOCKS certification method not match."
#define MSGJPN037		"Certification failed by SOCKS server."
#define MSGJPN038		"Name"
#define MSGJPN039		"Date"
#define MSGJPN040		"Size"
#define MSGJPN041		"Ext"
#define MSGJPN042		"Name"
#define MSGJPN043		"Date"
#define MSGJPN044		"Size"
#define MSGJPN045		"Ext"
#define MSGJPN046		"Permissions"
#define MSGJPN047		"Owner"
#define MSGJPN048		"Can't read temporary file."
#define MSGJPN049		"Failed to getting file list."
#define MSGJPN050		"Find (Local)"
#define MSGJPN051		"Find (Host)"
#define MSGJPN052		"Dele: %s"
#define MSGJPN053		"Make: %s"
#define MSGJPN054		"Tran: %s"
#define MSGJPN055		"Dele: %s"
#define MSGJPN056		"Make: %s"
#define MSGJPN057		"Tran: %s"
#define MSGJPN058		"Transfer %d files."
#define MSGJPN059		"No file to transmit."
#define MSGJPN060		"Create %d folders."
#define MSGJPN061		"No folder to create."
#define MSGJPN062		"Delete %d files/folders."
#define MSGJPN063		"No file/folder to delete."
#define MSGJPN064		"Upload as"
#define MSGJPN065		"Download as"
#define MSGJPN066		"Delete (Local)"
#define MSGJPN067		"Delete (Host)"
#define MSGJPN068		"Rename (Local)"
#define MSGJPN069		"Rename (Host)"
#define MSGJPN070		"New Filder (Local)"
#define MSGJPN071		"New Folder (Host)"
#define MSGJPN072		"Change Current Folder (Local)"
#define MSGJPN073		"Change Current Folder (Host)"
#define MSGJPN074		"Calculate local file size."
#define MSGJPN075		"Calculate host file size."
#define MSGJPN076		"Local file size"
#define MSGJPN077		"Host file size"
#define MSGJPN078		"New Folder"
#define MSGJPN079		"New Folder"
#define MSGJPN080		"Delete Folder"
#define MSGJPN081		"Delete File"
#define MSGJPN082		"New Folder"
#define MSGJPN083		"Delete Folder"
#define MSGJPN084		"Delete File"
#define MSGJPN085		"Can't download named %s."
#define MSGJPN086		"Download"
#define MSGJPN087		"File List"
#define MSGJPN088		"Skip"
#define MSGJPN089		"Skip file %s."
#define MSGJPN090		"Command not accepted."
#define MSGJPN091		"for download "
#define MSGJPN092		"Command not accepted."
#define MSGJPN093		"Can't get address."
#define MSGJPN094		"Time out error."
#define MSGJPN095		"Can't create file %s."
#define MSGJPN096		"Disk full"
#define MSGJPN097		"Cancel to getting file list"
#define MSGJPN098		"File List"
#define MSGJPN099		"Download cancelled. (%d Sec. %d B/S)."
#define MSGJPN100		"Download cancelled."
#define MSGJPN101		"Download file list successful. (%d Bytes)"
#define MSGJPN102		"Download successful. (%d Sec. %d B/S)."
#define MSGJPN103		"Download successful. (%d Bytes)"
#define MSGJPN104		"Upload"
#define MSGJPN105		"Can't read file %s."
#define MSGJPN106		"Skip"
#define MSGJPN107		"File %s is skipped."
#define MSGJPN108		"Command not accepted."
#define MSGJPN109		"for upload "
#define MSGJPN110		"Command not accepted."
#define MSGJPN111		"Can't get address."
#define MSGJPN112		"Can't open file %s."
#define MSGJPN113		"Upload cancelled. (%d Sec. %d B/S)."
#define MSGJPN114		"Upload cancelled."
#define MSGJPN115		"Upload successful. (%d Sec. %d B/S)."
#define MSGJPN116		"Upload successfil."
#define MSGJPN117		"Finished"
#define MSGJPN118		"Cancelled"
#define MSGJPN119		"BINARY"
#define MSGJPN120		"ASCII"
#define MSGJPN121		"NONE"
#define MSGJPN122		"JIS"
#define MSGJPN123		"EUC"
#define MSGJPN124		"Delete(Local)"
#define MSGJPN125		"Delete(Host)"
#define MSGJPN126		"WS_FTP.INI"
#define MSGJPN127		"General"
#define MSGJPN128		"Advanced"
#define MSGJPN129		"Kanji Code"
#define MSGJPN130		"Dialup"
#define MSGJPN131		"Special"
#define MSGJPN132		"Host Setting"
#define MSGJPN133		"GMT%+02d:00"
#define MSGJPN134		"None"
#define MSGJPN135		"Auto"
#define MSGJPN136		"OTP MD4, S/KEY"
#define MSGJPN137		"OTP MD5"
#define MSGJPN138		"OTP SHA-1"
#define MSGJPN139		"Auto"
#define MSGJPN140		"ACOS"
#define MSGJPN141		"VAX VMS"
#define MSGJPN142		"IRMX"
#define MSGJPN143		"ACOS-4"
#define MSGJPN144		"Stratus"
#define MSGJPN145		"Can't change folder."
#define MSGJPN146		"Can't create folder."
#define MSGJPN147		"Can't delete folder."
#define MSGJPN148		"Can't delete folder."
#define MSGJPN149		"Can't delete file."
#define MSGJPN150		"Can't delete file."
#define MSGJPN151		"Can't rename file."
#define MSGJPN152		"Temporary folder '%s' not found."
#define MSGJPN153		"Folder '%s' is used."
#define MSGJPN154		"Connect"
#define MSGJPN155		"Quick Connect"
#define MSGJPN156		"Disconnect"
#define MSGJPN157		"Download"
#define MSGJPN158		"Upload"
#define MSGJPN159		"Mirror Upload"
#define MSGJPN160		"Delete"
#define MSGJPN161		"Rename"
#define MSGJPN162		"New Folder"
#define MSGJPN163		"Parent Folder"
#define MSGJPN164		"Change Folder"
#define MSGJPN165		"ASCII Mode"
#define MSGJPN166		"BINARY Mode"
#define MSGJPN167		"Filename Depend"
#define MSGJPN168		"Refresh File List"
#define MSGJPN169		"List"
#define MSGJPN170		"Details"
#define MSGJPN171		"EUC Kanji Code"
#define MSGJPN172		"JIS Kanji Code"
#define MSGJPN173		"NO Kanji Conversin"
#define MSGJPN174		"Hankaku-Kana to Zenkaku"
#define MSGJPN175		"Sync. folder movement"
#define MSGJPN176		"Stop"
#define MSGJPN177		"Host profile '%s' not found."
#define MSGJPN178		"Host profile not specified."
#define MSGJPN179		"Host name is only used as an alternative to profile name."
#define MSGJPN180		"Wrong Option '%s'."
#define MSGJPN181		"Host name is only used as an alternative to profile name."
#define MSGJPN182		"Failed to open viewer. (ERROR=%d)"
#define MSGJPN183		"JRE32.DLL none"
#define MSGJPN184		"JRE32.DLL Ver %x.%x (C) Kazuo Yamada-san"
#define MSGJPN185		"Select folder."
#define MSGJPN186		"User"
#define MSGJPN187		"Transfer1"
#define MSGJPN188		"Transfer2"
#define MSGJPN189		"Transfer3"
#define MSGJPN190		"Mirroring"
#define MSGJPN191		"Operation"
#define MSGJPN192		"View"
#define MSGJPN193		"Connecting"
#define MSGJPN194		"Firewall"
#define MSGJPN195		"Tool"
#define MSGJPN196		"Sounds"
#define MSGJPN197		"Other"
#define MSGJPN198		"Option"
#define MSGJPN199		"Filename"
#define MSGJPN200		"Filename"
#define MSGJPN201		"Attr"
#define MSGJPN202		"Filename"
#define MSGJPN203		"Filename"
#define MSGJPN204		"FW user-> FW password-> SITE host"
#define MSGJPN205		"FW user-> FW password-> USER user@host"
#define MSGJPN206		"FW user-> FW password"
#define MSGJPN207		"USER user@host"
#define MSGJPN208		"OPEN host"
#define MSGJPN209		"SOCKS4"
#define MSGJPN210		"SOCKS5 (No certification)"
#define MSGJPN211		"SOCKS5 (User, Password certification)"
#define MSGJPN212		"None"
#define MSGJPN213		"Auto"
#define MSGJPN214		"OTP MD4,S/KEY"
#define MSGJPN215		"OTP MD5"
#define MSGJPN216		"OTP SHA-1"
#define MSGJPN217		"Select viewer"
#define MSGJPN218		"EXE file\0*.exe;*.com;*.bat\0All file(*.*)\0*\0"
#define MSGJPN219		"Wave file"
#define MSGJPN220		"Disconencting dialup."
#define MSGJPN221		"Connecting dialup."
#define MSGJPN222		"Can't use dialup. (RasDialDlg)"
#define MSGJPN223		"Connecting to %s..."
#define MSGJPN224		"Unknown error"
#define MSGJPN225		"Dialup connection"
#define MSGJPN226		"Open port..."
#define MSGJPN227		"Port opened."
#define MSGJPN228		"Dialing..."
#define MSGJPN229		"Dialed."
#define MSGJPN230		"All device connected."
#define MSGJPN231		"Authenticating..."
#define MSGJPN232		"Authenticate retry..."
#define MSGJPN233		"Please change password."
#define MSGJPN234		"Authenticated."
#define MSGJPN235		"Connected"
#define MSGJPN236		"Disconnected."
#define MSGJPN237		"Connecting..."
#define MSGJPN238		"Connecting to %s"
#define MSGJPN239		"# Do not edit this file.\n"
#define MSGJPN240		"Can't save to INI file"
#define MSGJPN241		"Failed transmit cause of timeout"
#define MSGJPN242		"Failed receive cause of timeout"
#define MSGJPN243		"Failed receive cause of timeout"
#define MSGJPN244		"Receive length error"
#define MSGJPN245		"Local"
#define MSGJPN246		"Host"
#define MSGJPN247		"Selected: %d (%s)"
#define MSGJPN248		"Local free: %s"
#define MSGJPN249		"Files in queue: %d"
#define MSGJPN250		"Receiving %s"
#define MSGJPN251		"Err\xEF\xBC\x9ASeed"
#define MSGJPN252		"Err\xEF\xBC\x9ASeed"
#define MSGJPN253		"Err\xEF\xBC\x9ASequence#"
#define MSGJPN254		"MS Sans Serif"
#define MSGJPN255		"&Upload"
#define MSGJPN256		"U&pload As..."
#define MSGJPN257		"Up&load All"
#define MSGJPN258		"&Delete"
#define MSGJPN259		"&Rename..."
#define MSGJPN260		"&New Folder..."
#define MSGJPN261		"&File Size..."
#define MSGJPN262		"R&efresh File List"
#define MSGJPN263		"&Download"
#define MSGJPN264		"D&ownload As..."
#define MSGJPN265		"Do&wnliad as File"
#define MSGJPN266		"Dow&nload All"
#define MSGJPN267		"De&lete..."
#define MSGJPN268		"&Rename..."
#define MSGJPN269		"&Change Permission..."
#define MSGJPN270		"&New Folder..."
#define MSGJPN271		"Copy &URL to Clipboard"
#define MSGJPN272		"&File Size..."
#define MSGJPN273		"R&efresh File List"
#define MSGJPN274		"&Open"
#define MSGJPN275		"Open in %s (&%d)"
#define MSGJPN276		"WS_FTP.INI\0ws_ftp.ini\0All file(*.*)\0*\0"
#define MSGJPN277		"Wave file\0*.wav\0All file\0*\0"
#define MSGJPN278		"Reason : %s"
#define MSGJPN279		"Can't get Listen Socket"
#define MSGJPN280		"Can't get Data Socket"
#define MSGJPN281		"Can't connect with PASV mode"
#define MSGJPN282		"INI filename is not specified"
#define MSGJPN283		"INI file : "
#define MSGJPN284		"http://sourceforge.jp/projects/ffftp/"
#define MSGJPN285		"Failed to execute Registory Editor."
#define MSGJPN286		"Save Settings"
#define MSGJPN287		"Reg file\0*.reg\0All file\0*\0"
#define MSGJPN288		"INI file\0*.ini\0All file\0*\0"
#define MSGJPN289		"Agilent Logic analyzer"
#define MSGJPN290		"Reg file\0*.reg\0INI file\0*.ini\0All files\0*\0"
#define MSGJPN291		"Load Settings"
#define MSGJPN292		"Restart FFFTP to take effect."
#define MSGJPN293		"File must be *.reg or *.ini."
#define MSGJPN294		"USER FW user:FW password@host"
#define MSGJPN295		"ShibaSoku WL"
#define MSGJPN296		"This is a read-only file. Remove the read-only attribute?"
#define MSGJPN297		"%s is invalid path.\r\nFFFTP doesn't download this file."
#define MSGJPN298		"Failed to initialize the OLE."
#define MSGJPN299		"Master password is not specified in the command line"
#define MSGJPN300		"Default master password is chosen.\r\nSet your own master password in command line to prevent sniff of malwares"
#define MSGJPN301		"Master password is not for the current configuration. Configration will not be overwritten in this session."
#define MSGJPN302		"Master password checker looks broken."
#define MSGJPN303		"Master password has been changed."
#define MSGJPN304		"Speecified master password is not correct.\r\nAre you sure you want to re-enter?\r\nNo memorized FTP password is available if you choose 'NO'"
#define MSGJPN305		"Shift_JIS"
#define MSGJPN306		"UTF-8"
#define MSGJPN307		"Shift_JIS Kanji Code"
#define MSGJPN308		"UTF-8 Kanji Code"
#define MSGJPN309		"Shift_JIS Kanji Code (Local)"
#define MSGJPN310		"EUC Kanji Code (Local)"
#define MSGJPN311		"JIS Kanji Code (Local)"
#define MSGJPN312		"UTF-8 Kanji Code (Local)"
#define MSGJPN313		"Encryption"
#define MSGJPN314		"Communication is not encrypted.\r\nPassword and other data may be intercepted by a third party."
#define MSGJPN315		"Using FTP over Explicit SSL/TLS (FTPES)."
#define MSGJPN316		"Using FTP over Implicit SSL/TLS (FTPIS)."
#define MSGJPN317		"Using SSH FTP (SFTP)."
#define MSGJPN318		"OpenSSL is loaded."
#define MSGJPN319		"OpenSSL is not installed.\r\nCommunication will not be encrypted."
#define MSGJPN320		"Feature"
#define MSGJPN321		"Failed to get required functions to protect the process."
#define MSGJPN322		"Debugger was detected."
#define MSGJPN323		"Failed to unload untrustworthy DLLs."
#define MSGJPN324		"Failed to hook required functions to protect the process."
#define MSGJPN325		"New master passwords are not identical."
#define MSGJPN326		"Choose 'Yes' if you trust this certificate and continue.\r\nCN is identical: %s\r\nVerified successfully: %s\r\n\r\n%s"
#define MSGJPN327		"Yes"
#define MSGJPN328		"No"
#define MSGJPN329		"UTF-8 BOM"
#define MSGJPN330		"UTF-8 BOM Kanji Code"
#define MSGJPN331		"UTF-8 BOM Kanji Code (Local)"
#define MSGJPN332		"Auto"
#define MSGJPN333		"TCP/IPv4"
#define MSGJPN334		"TCP/IPv6"
#define MSGJPN335		"Ask everytime"
#define MSGJPN336		"Overwrite all later"
#define MSGJPN337		"Resume all later"
#define MSGJPN338		"Skip all"
